project_name: libresign

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - dir: ./cmd/libresign/
    hooks:
      post:
        - upx "{{ .Path }}"
    ldflags:
      - -s
      - -w
      - -extldflags=-static
    flags:
      - -a
      - -installsuffix=cgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - format: binary
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
